### PR TITLE
Various syntax and additions to the workshop.

### PR DESCRIPTION
**Pull request by blogh**
Hi,

Here are a few modifications. I'll continue adding stuff once you're done with your own modifications.

Benoit.

### CODE REVIEW

**Comment by blogh** [comment]
I noticed some typos in my modifications...
If it's ok with you, I'll do a clean PR if you re cool with the content of this one.

**Comment by blogh** [comment]
I will have to deal with it ... it's too late, the internet knows now ...

**Comment by ioguix** [comment]
Github is struggling weirdly with this PR.

I did merged it, it appears in the commits, but it is still "open" in a weird state... Not sure what to do with it. Let's wait some days if github fall back on its feet.

**Comment by blogh** [comment]
Thx !

**Pull request merged**
